[client]
toolbarMode = "minimal"

[logger]
level = "warning"

[theme]
primaryColor = "#0000FF"
backgroundColor = "#CF9FFF"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#000000"
font="sans serif"

[browser]
gatherUsageStats = false
