[client]
toolbarMode = "minimal"

[logger]
level = "warning"

[theme]
primaryColor = "#0000FF"
backgroundColor = "#000000"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#CBC3E3"
font="sans serif"

[browser]
gatherUsageStats = false
